a=input()
print(a)
b=int(input())
a=int(input("enter a number"))
b=input(input("enter another number"))
print(a+b)
r=input(input("Enter the radius of the circle"))
pie=3.14
area=p*(r**2)
print("area of the square is :",area)
a=int(input())
print(a**2)
a=int(input("enter the base of the traingle"))
b=int(input("enter the height of the triangle"))
area=(0.5)*a*b
print("Area of the tirangle :",area)
a,b,c=input().split()
a,b,c=int(a),int(b),int(c)
print((a+b+C)/3)
print("Volume of cubiod is :",(a*b*C))
a=int(input("enter length of cubiod"))
b=int(input("enter breadth of cubiod"))
print("area of rectangle",a*b)
